// @generated
// This file is autogenerated, do not edit manually

/** [See route renderer](./Root_route_renderer.res)*/
module Root = {
  module Route = Route__Root_route

}
/** [See route renderer](./Other_route_renderer.res)*/
module Other = {
  module Route = Route__Other_route

}
/** [See route renderer](./FourOhFour_route_renderer.res)*/
module FourOhFour = {
  module Route = Route__FourOhFour_route

}