// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_HashMapString from "rescript/lib/es6/belt_HashMapString.js";
import * as RelayRouter__Internal__DeclarationsSupport from "rescript-relay-router/src/RelayRouter__Internal__DeclarationsSupport.bs.mjs";

var loadedRouteRenderers = Belt_HashMapString.make(3);

function make(prepareDisposeTimeoutOpt) {
  var prepareDisposeTimeout = prepareDisposeTimeoutOpt !== undefined ? prepareDisposeTimeoutOpt : 300000;
  var match = RelayRouter__Internal__DeclarationsSupport.makePrepareAssets(loadedRouteRenderers, prepareDisposeTimeout);
  var prepareRoute = match.prepareRoute;
  var getPrepared = match.getPrepared;
  var routeName = "Root";
  var loadRouteRenderer = function () {
    return RelayRouter__Internal__DeclarationsSupport.doLoadRouteRenderer((function () {
                  return import("../Root_route_renderer.bs.mjs").then(function (m) {
                              return m.renderer;
                            });
                }), routeName, loadedRouteRenderers);
  };
  var makePrepareProps = function (environment, pathParams, queryParams, $$location) {
    return {
            environment: environment,
            location: $$location
          };
  };
  var routeName$1 = "Other";
  var loadRouteRenderer$1 = function () {
    return RelayRouter__Internal__DeclarationsSupport.doLoadRouteRenderer((function () {
                  return import("../Other_route_renderer.bs.mjs").then(function (m) {
                              return m.renderer;
                            });
                }), routeName$1, loadedRouteRenderers);
  };
  var makePrepareProps$1 = function (environment, pathParams, queryParams, $$location) {
    return {
            environment: environment,
            location: $$location
          };
  };
  var routeName$2 = "FourOhFour";
  var loadRouteRenderer$2 = function () {
    return RelayRouter__Internal__DeclarationsSupport.doLoadRouteRenderer((function () {
                  return import("../FourOhFour_route_renderer.bs.mjs").then(function (m) {
                              return m.renderer;
                            });
                }), routeName$2, loadedRouteRenderers);
  };
  var makePrepareProps$2 = function (environment, pathParams, queryParams, $$location) {
    return {
            environment: environment,
            location: $$location
          };
  };
  return [
          {
            path: "/",
            name: routeName,
            __$rescriptChunkName__: "Root_route_renderer",
            loadRouteRenderer: loadRouteRenderer,
            preloadCode: (function (environment, pathParams, queryParams, $$location) {
                return RelayRouter__Internal__DeclarationsSupport.preloadCode(loadedRouteRenderers, routeName, loadRouteRenderer, makePrepareProps, environment, pathParams, queryParams, $$location);
              }),
            prepare: (function (environment, pathParams, queryParams, $$location, intent) {
                return prepareRoute(environment, pathParams, queryParams, $$location, makePrepareProps, (function (pathParams, queryParams) {
                              return "Root:";
                            }), getPrepared, routeName, loadRouteRenderer, intent);
              }),
            children: []
          },
          {
            path: "/other",
            name: routeName$1,
            __$rescriptChunkName__: "Other_route_renderer",
            loadRouteRenderer: loadRouteRenderer$1,
            preloadCode: (function (environment, pathParams, queryParams, $$location) {
                return RelayRouter__Internal__DeclarationsSupport.preloadCode(loadedRouteRenderers, routeName$1, loadRouteRenderer$1, makePrepareProps$1, environment, pathParams, queryParams, $$location);
              }),
            prepare: (function (environment, pathParams, queryParams, $$location, intent) {
                return prepareRoute(environment, pathParams, queryParams, $$location, makePrepareProps$1, (function (pathParams, queryParams) {
                              return "Other:";
                            }), getPrepared, routeName$1, loadRouteRenderer$1, intent);
              }),
            children: []
          },
          {
            path: "*",
            name: routeName$2,
            __$rescriptChunkName__: "FourOhFour_route_renderer",
            loadRouteRenderer: loadRouteRenderer$2,
            preloadCode: (function (environment, pathParams, queryParams, $$location) {
                return RelayRouter__Internal__DeclarationsSupport.preloadCode(loadedRouteRenderers, routeName$2, loadRouteRenderer$2, makePrepareProps$2, environment, pathParams, queryParams, $$location);
              }),
            prepare: (function (environment, pathParams, queryParams, $$location, intent) {
                return prepareRoute(environment, pathParams, queryParams, $$location, makePrepareProps$2, (function (pathParams, queryParams) {
                              return "FourOhFour:";
                            }), getPrepared, routeName$2, loadRouteRenderer$2, intent);
              }),
            children: []
          }
        ];
}

export {
  make ,
}
/* loadedRouteRenderers Not a pure module */
