// Generated by ReScript, PLEASE EDIT WITH CARE


var Root = {
  Route: undefined
};

var Other = {
  Route: undefined
};

var FourOhFour = {
  Route: undefined
};

export {
  Root ,
  Other ,
  FourOhFour ,
}
/* No side effect */
