// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as PageNotFound$Frontend from "../PageNotFound.bs.mjs";

var renderer = {
  prepare: (function (_props) {
      
    }),
  render: (function (_props) {
      return JsxRuntime.jsx(PageNotFound$Frontend.make, {});
    })
};

export {
  renderer ,
}
/* react/jsx-runtime Not a pure module */
