// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Other$Frontend from "../Other.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var renderer = {
  prepare: (function (_props) {
      
    }),
  render: (function (_props) {
      return JsxRuntime.jsx(Other$Frontend.make, {});
    })
};

export {
  renderer ,
}
/* Other-Frontend Not a pure module */
