// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Root$Frontend from "../Root.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var renderer = {
  prepare: (function (_props) {
      
    }),
  render: (function (_props) {
      return JsxRuntime.jsx(Root$Frontend.make, {});
    })
};

export {
  renderer ,
}
/* Root-Frontend Not a pure module */
