// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import ViteSvg from "/vite.svg";
import * as StringExt$Common from "common/src/StringExt.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import ReactSvg from "./assets/react.svg";

import './App.css'
;

var reactLogo = ReactSvg;

function App(props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("a", {
                              children: JsxRuntime.jsx("img", {
                                    className: "logo",
                                    alt: "Vite logo",
                                    src: ViteSvg
                                  }),
                              href: "https://vitejs.dev",
                              target: "_blank"
                            }),
                        JsxRuntime.jsx("a", {
                              children: JsxRuntime.jsx("img", {
                                    className: "logo react",
                                    alt: "React logo",
                                    src: reactLogo
                                  }),
                              href: "https://react.dev",
                              target: "_blank"
                            })
                      ]
                    }),
                JsxRuntime.jsx("h1", {
                      children: "Vite + React"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "count is " + match[0].toString(),
                              onClick: (function (param) {
                                  setCount(function (count) {
                                        return count + 1 | 0;
                                      });
                                })
                            }),
                        JsxRuntime.jsxs("p", {
                              children: [
                                "Edit ",
                                JsxRuntime.jsx("code", {
                                      children: StringExt$Common.combinePaths("src", "App.res")
                                    }),
                                " and save to test HMR"
                              ]
                            })
                      ],
                      className: "card"
                    }),
                JsxRuntime.jsx("p", {
                      children: "Click on the Vite and React logos to learn more",
                      className: "read-the-docs"
                    })
              ]
            });
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
