// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RelayRouter from "rescript-relay-router/src/RelayRouter.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx(RelayRouter.RouteRenderer.make, {
              renderPending: (function (pending) {
                  return JsxRuntime.jsx("div", {
                              children: pending ? "Loading..." : null
                            });
                })
            });
}

var make = App;

export {
  make ,
}
/* RelayRouter Not a pure module */
