// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as RelayRouter from "rescript-relay-router/src/RelayRouter.bs.mjs";
import * as App$Frontend from "./App.bs.mjs";
import * as Router$Frontend from "./Router.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactErrorBoundary from "@rescript/react/src/RescriptReactErrorBoundary.bs.mjs";

function Index(props) {
  return JsxRuntime.jsx(RelayRouter.Provider.make, {
              value: Router$Frontend.routerContext,
              children: JsxRuntime.jsx(React.Suspense, {
                    children: Caml_option.some(JsxRuntime.jsx(RescriptReactErrorBoundary.make, {
                              children: JsxRuntime.jsx(App$Frontend.make, {}),
                              fallback: (function (param) {
                                  return "Error!";
                                })
                            })),
                    fallback: "Loading..."
                  })
            });
}

var make = Index;

export {
  make ,
}
/* react Not a pure module */
