// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as RelayRouter from "rescript-relay-router/src/RelayRouter.bs.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.mjs";
import * as RescriptCore from "@rescript/core/src/RescriptCore.bs.mjs";
import * as RescriptRelay from "rescript-relay/src/RescriptRelay.bs.mjs";
import * as RelayRuntime from "relay-runtime";
import * as RouteDeclarations$Frontend from "./routes/__generated__/RouteDeclarations.bs.mjs";
import * as RelayRouter__AssetPreloader from "rescript-relay-router/src/RelayRouter__AssetPreloader.bs.mjs";

async function fetchQuery(operation, variables, _cacheConfig, _uploadables) {
  var resp = await fetch("http://localhost:4000/graphql", {
        method: "POST",
        body: Caml_option.some(Core__Option.getExn(JSON.stringify({
                      query: operation.text,
                      variables: variables
                    }), undefined)),
        headers: Caml_option.some(new Headers({
                  "content-type": "application/json",
                  accept: "application/json"
                }))
      });
  if (resp.ok) {
    return await resp.json();
  } else {
    return RescriptCore.panic("Request failed: " + resp.statusText);
  }
}

var network = RelayRuntime.Network.create(fetchQuery);

var environment = RescriptRelay.Environment.make(network, RescriptRelay.Store.make(new RelayRuntime.RecordSource(), 10, undefined), undefined, undefined, undefined, undefined, undefined);

var preparedAssetsMap = {};

var match = RelayRouter.Router.make(RouteDeclarations$Frontend.make(300000), RelayRouter.RouterEnvironment.makeBrowserEnvironment(), environment, RelayRouter__AssetPreloader.makeClientAssetPreloader(preparedAssetsMap));

var _cleanup = match[0];

var routerContext = match[1];

export {
  fetchQuery ,
  network ,
  environment ,
  preparedAssetsMap ,
  _cleanup ,
  routerContext ,
}
/* network Not a pure module */
