// Generated by ReScript, PLEASE EDIT WITH CARE


function combinePaths(path1, path2) {
  return path1 + "/" + path2;
}

function combinePaths3(path1, path2, path3) {
  return path1 + "/" + path2 + "/" + path3;
}

export {
  combinePaths ,
  combinePaths3 ,
}
/* No side effect */
